Finds first code cell for imports
8080labs/pyforest pull request #29
Opened 2020-01-19 16:29 UTC by tnwei

Pull request to address #27

2020-01-20 07:00 UTC, 8080labs requested changes
Thank you for the PR! :)
Please have a look at the comment and change accordingly. If something is unclear, please let us know

2020-01-20 07:00 UTC, 8080labs commented on src/pyforest/static/utils.js
> +		  for (var i = 0; i < cells.length; i++) {
Should have the same indentation as the line before

2020-01-20 07:00 UTC, 8080labs commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
JupyterLab needs a different logic - the above logic only works in Jupyter Notebook

2020-01-20 07:00 UTC, 8080labs commented on src/pyforest/static/utils.js
> +	window.findFirstCodeCell = function findFirstCodeCell() {
Try to use the new function without adding it to window because we don't want to spam the users window functions

2020-01-20 07:01 UTC, 8080labs commented on src/pyforest/static/utils.js
> +		  for (var i = 0; i < cells.length; i++) {
I mean the diff between `var cells` and the `for` block

2020-01-21 16:15 UTC, tnwei commented on src/pyforest/static/utils.js
> +		  for (var i = 0; i < cells.length; i++) {
Aha right thanks for pointing this out

2020-01-21 16:17 UTC, tnwei commented on src/pyforest/static/utils.js
> +	window.findFirstCodeCell = function findFirstCodeCell() {
Removed from window namespace

2020-01-29 12:46 UTC, tnwei commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
Been looking at this for a while, can you give me some tips on what I should be focused on? A bit lost navigating the differences between Notebook and Lab.

2020-01-31 18:07 UTC, 8080labs commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
Sorry, but I also did not work with this so far. You might try to get all the cells and then read the type for each cell. Similar to the Jupyter Notebook logic. The code is just a little bit different for the notebook. Biggest challenge might be to debug this in order to inspect whats available.

You might look at this here and then go from there:
https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html#structure-of-the-notebook-plugin

https://jupyterlab.github.io/jupyterlab/cells/classes/cellmodel.html

2020-02-10 18:38 UTC, tnwei commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
I believe the building blocks required sit here: https://jupyterlab.github.io/jupyterlab/cells/globals.html#iscodecellmodel, just need to find a way to get this into the code. Kept running into JLab build issues, so this is going to take a while.

2020-02-11 08:39 UTC, 8080labs commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
Alright, thank you for letting us know and hang in there - we know that struggle! 👍

2021-06-11 13:49 UTC, tkrabel commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
Any progress on this front?

2021-06-14 14:53 UTC, tkrabel commented on src/pyforest/static/utils.js
> +			var cell = notebookTracker.currentWidget.model.cells.get(findFirstCodeCell()).value;
Solved with PR #46

2021-06-14 14:54 UTC, tkrabel commented
This can be closed now. I added JupyterLab support myself in PR #46.

2021-06-14 14:54 UTC, closed without merging